;this file for FamiTone2 library generated by text2data tool

bad_apple_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; New song

@instruments:
	.byte $70 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $70 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env4,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cf,$ce,$ce,$cd,$cd,$cc,$03,$cb,$cb,$ca,$ca,$c9,$02,$c8,$c8
	.byte $c7,$c6,$c5,$c5,$c4,$c4,$c3,$c2,$c1,$c1,$c0,$00,$1a
@env2:
	.byte $cf,$04,$cc,$ca,$c9,$c7,$c4,$c0,$00,$07
@env3:
	.byte $cf,$c5,$c7,$c8,$c9,$c8,$c8,$c7,$c7,$c6,$c5,$c4,$c3,$c2,$c0,$00
	.byte $0e
@env4:
	.byte $cf,$cf,$ce,$cc,$cb,$c9,$c6,$c4,$c3,$c4,$c4,$c5,$06,$c4,$02,$c3
	.byte $ca,$ca,$c9,$c9,$c8,$c7,$c7,$c6,$c5,$c5,$c4,$c2,$c1,$c1,$c0,$00
	.byte $1e


; New song
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $f9,$85
@ref1:
	.byte $f9,$85
@ref2:
	.byte $82,$39,$38,$51,$50,$4c,$50,$39,$38,$51,$50,$4c,$50,$39,$38,$51
	.byte $50,$4c,$50,$51,$56,$50,$5b,$56,$5a,$39,$38,$51,$50,$4c,$50,$39
	.byte $38,$51,$50,$4c,$50,$39,$38,$51,$50,$4c,$50,$5b,$56,$5a,$57,$50
	.byte $56
@ref3:
	.byte $39,$38,$51,$50,$4c,$50,$39,$38,$51,$50,$4c,$50,$39,$38,$51,$50
	.byte $4c,$50,$51,$56,$50,$5b,$56,$5a,$39,$38,$51,$50,$4c,$50,$39,$38
	.byte $51,$50,$4c,$50,$39,$38,$51,$50,$4c,$50,$5b,$56,$5a,$57,$50,$56
@ref4:
	.byte $80,$39,$3d,$3f,$43,$46,$85,$51,$4d,$46,$85,$38,$85,$47,$43,$3f
	.byte $3d,$39,$3d,$3f,$43,$46,$85,$43,$3f,$3d,$39,$3d,$3f,$3d,$39,$37
	.byte $3c,$81
@ref5:
	.byte $39,$3d,$3f,$43,$46,$85,$51,$4d,$46,$85,$38,$85,$47,$43,$3f,$3d
	.byte $39,$3d,$3f,$43,$46,$85,$43,$3f,$3c,$85,$3e,$85,$42,$85,$46,$85
@ref6:
	.byte $39,$3d,$3f,$43,$46,$85,$51,$4d,$46,$85,$38,$85,$47,$43,$3f,$3d
	.byte $39,$3d,$3f,$43,$46,$85,$43,$3f,$3d,$39,$3d,$3f,$3d,$39,$37,$3c
	.byte $81
	.byte $ff,$20
	.word @ref5
@ref8:
	.byte $4d,$51,$47,$43,$46,$85,$43,$47,$4d,$51,$47,$43,$46,$85,$43,$47
	.byte $43,$3f,$3d,$35,$38,$85,$35,$39,$3d,$3f,$43,$47,$38,$85,$43,$46
	.byte $81
	.byte $ff,$21
	.word @ref8
	.byte $ff,$21
	.word @ref8
@ref11:
	.byte $4d,$51,$47,$43,$46,$85,$43,$47,$4d,$51,$47,$43,$46,$85,$51,$55
	.byte $57,$55,$51,$4d,$46,$85,$43,$47,$43,$3f,$3d,$35,$38,$8d
	.byte $ff,$21
	.word @ref8
	.byte $ff,$21
	.word @ref8
	.byte $ff,$21
	.word @ref8
	.byte $ff,$1e
	.word @ref11
	.byte $ff,$30
	.word @ref2
	.byte $ff,$30
	.word @ref3
	.byte $ff,$21
	.word @ref4
	.byte $ff,$20
	.word @ref5
	.byte $ff,$21
	.word @ref6
	.byte $ff,$20
	.word @ref5
	.byte $ff,$21
	.word @ref8
	.byte $ff,$21
	.word @ref8
	.byte $ff,$21
	.word @ref8
	.byte $ff,$1e
	.word @ref11
	.byte $ff,$21
	.word @ref8
	.byte $ff,$21
	.word @ref8
	.byte $ff,$21
	.word @ref8
@ref29:
	.byte $4d,$51,$47,$43,$46,$85,$43,$47,$4d,$51,$47,$43,$46,$85,$51,$55
	.byte $57,$55,$51,$4d,$46,$85,$43,$47,$43,$3f,$3d,$35,$38,$85,$45,$48
	.byte $81
@ref30:
	.byte $4f,$53,$49,$45,$48,$85,$45,$49,$4f,$53,$49,$45,$48,$85,$45,$49
	.byte $45,$41,$3f,$37,$3a,$85,$37,$3b,$3f,$41,$45,$49,$3a,$85,$45,$48
	.byte $81
	.byte $ff,$21
	.word @ref30
	.byte $ff,$21
	.word @ref30
@ref33:
	.byte $4f,$53,$49,$45,$48,$85,$45,$49,$4f,$53,$49,$45,$48,$85,$3b,$3f
	.byte $41,$3f,$3b,$37,$30,$85,$45,$49,$45,$41,$3f,$37,$3a,$8d
@ref34:
	.byte $3a,$83,$3a,$83,$36,$36,$36,$3a,$83,$3a,$83,$36,$36,$36,$3a,$83
	.byte $3a,$83,$36,$36,$36,$3a,$83,$3a,$83,$36,$36,$36,$3a,$83,$3a,$83
	.byte $36,$36,$36,$3a,$83,$3a,$83,$36,$36,$36,$3a,$83,$3a,$83,$36,$36
	.byte $36,$3a
@ref35:
	.byte $83,$3a,$83,$3a,$3a
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref36:
	.byte $f9,$85
@ref37:
	.byte $f9,$85
@ref38:
	.byte $f9,$85
@ref39:
	.byte $f9,$85
@ref40:
	.byte $80,$2f,$35,$39,$3d,$3e,$85,$3f,$47,$3e,$85,$2e,$85,$3f,$3d,$39
	.byte $35,$2f,$35,$39,$3d,$3e,$85,$3d,$39,$35,$2f,$35,$39,$35,$2f,$2b
	.byte $38,$81
@ref41:
	.byte $2f,$35,$39,$3d,$3e,$85,$3f,$47,$3e,$85,$2e,$85,$3f,$3d,$39,$35
	.byte $2f,$35,$39,$3d,$3e,$85,$3d,$39,$34,$85,$38,$85,$3c,$85,$3e,$85
@ref42:
	.byte $2f,$35,$39,$3d,$3e,$85,$3f,$47,$3e,$85,$2e,$85,$3f,$3d,$39,$35
	.byte $2f,$35,$39,$3d,$3e,$85,$3d,$39,$35,$2f,$35,$39,$35,$2f,$2b,$38
	.byte $81
	.byte $ff,$20
	.word @ref41
@ref44:
	.byte $43,$49,$3f,$3d,$3e,$85,$3d,$3f,$43,$3f,$3f,$3d,$3e,$85,$3d,$3f
	.byte $3d,$39,$35,$2b,$2e,$85,$2b,$2f,$35,$39,$3d,$3f,$2e,$85,$3d,$3e
	.byte $81
	.byte $ff,$21
	.word @ref44
	.byte $ff,$21
	.word @ref44
@ref47:
	.byte $43,$49,$3f,$3d,$3e,$85,$3d,$3f,$43,$3f,$3f,$3d,$3e,$85,$49,$4d
	.byte $51,$4d,$49,$43,$3e,$85,$3d,$3f,$3d,$39,$35,$2b,$2e,$8d
@ref48:
	.byte $f9,$85
@ref49:
	.byte $f9,$85
@ref50:
	.byte $f9,$85
@ref51:
	.byte $f9,$85
@ref52:
	.byte $f9,$85
@ref53:
	.byte $f9,$85
	.byte $ff,$21
	.word @ref42
	.byte $ff,$20
	.word @ref41
	.byte $ff,$21
	.word @ref42
	.byte $ff,$20
	.word @ref41
	.byte $ff,$21
	.word @ref44
	.byte $ff,$21
	.word @ref44
	.byte $ff,$21
	.word @ref44
	.byte $ff,$1e
	.word @ref47
@ref62:
	.byte $f9,$85
@ref63:
	.byte $f9,$85
@ref64:
	.byte $f9,$85
@ref65:
	.byte $f7,$3f,$40,$81
@ref66:
	.byte $49,$4b,$41,$3f,$40,$85,$3f,$41,$49,$4b,$41,$3f,$40,$85,$3f,$41
	.byte $3f,$3b,$37,$31,$32,$85,$49,$45,$4f,$53,$57,$59,$44,$85,$3f,$40
	.byte $81
	.byte $ff,$21
	.word @ref66
	.byte $ff,$21
	.word @ref66
@ref69:
	.byte $49,$4b,$41,$3f,$40,$85,$3f,$41,$49,$4b,$41,$3f,$40,$85,$45,$49
	.byte $53,$49,$45,$41,$3a,$85,$3f,$41,$3f,$3b,$37,$2d,$30,$8d
@ref70:
	.byte $30,$83,$30,$83,$2c,$2c,$2c,$30,$83,$30,$83,$2c,$2c,$2c,$30,$83
	.byte $30,$83,$2c,$2c,$2c,$30,$83,$30,$83,$2c,$2c,$2c,$30,$83,$30,$83
	.byte $2c,$2c,$2c,$30,$83,$30,$83,$2c,$2c,$2c,$30,$83,$30,$83,$2c,$2c
	.byte $2c,$30
@ref71:
	.byte $83,$30,$83,$30,$30
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref72:
	.byte $f9,$85
@ref73:
	.byte $f9,$85
	.byte $ff,$30
	.word @ref2
	.byte $ff,$30
	.word @ref3
@ref76:
	.byte $39,$50,$51,$50,$4c,$50,$51,$50,$51,$50,$4c,$50,$51,$50,$51,$50
	.byte $4c,$50,$51,$56,$50,$5b,$56,$5a,$49,$48,$49,$48,$46,$48,$49,$48
	.byte $49,$48,$46,$48,$4d,$4c,$4d,$4c,$48,$4c,$51,$50,$56,$5b,$56,$5a
	.byte $ff,$30
	.word @ref76
	.byte $ff,$30
	.word @ref76
	.byte $ff,$30
	.word @ref76
@ref80:
	.byte $49,$48,$49,$48,$46,$48,$49,$48,$49,$48,$46,$48,$4d,$4c,$4d,$4c
	.byte $48,$4c,$4d,$52,$4c,$57,$52,$56,$51,$50,$51,$50,$4c,$50,$51,$50
	.byte $51,$50,$4c,$50,$51,$50,$51,$50,$4c,$50,$51,$56,$50,$5b,$56,$5a
	.byte $ff,$30
	.word @ref80
	.byte $ff,$30
	.word @ref80
	.byte $ff,$30
	.word @ref80
@ref84:
	.byte $f9,$85
@ref85:
	.byte $f9,$85
@ref86:
	.byte $f9,$85
@ref87:
	.byte $f9,$85
	.byte $ff,$30
	.word @ref3
	.byte $ff,$30
	.word @ref3
	.byte $ff,$30
	.word @ref76
	.byte $ff,$30
	.word @ref76
	.byte $ff,$30
	.word @ref76
	.byte $ff,$30
	.word @ref76
	.byte $ff,$30
	.word @ref80
	.byte $ff,$30
	.word @ref80
	.byte $ff,$30
	.word @ref80
	.byte $ff,$30
	.word @ref80
@ref98:
	.byte $f9,$85
@ref99:
	.byte $f9,$85
@ref100:
	.byte $f9,$85
@ref101:
	.byte $f9,$85
@ref102:
	.byte $f9,$85
@ref103:
	.byte $f9,$85
@ref104:
	.byte $f9,$85
@ref105:
	.byte $f9,$85
@ref106:
	.byte $80,$3a,$83,$3a,$83,$36,$36,$36,$3a,$83,$3a,$83,$36,$36,$36,$3a
	.byte $83,$3a,$83,$36,$36,$36,$3a,$83,$3a,$83,$36,$36,$36,$3a,$83,$3a
	.byte $83,$36,$36,$36,$3a,$83,$3a,$83,$36,$36,$36,$3a,$83,$3a,$83,$36
	.byte $36,$36,$3a
@ref107:
	.byte $8d
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref108:
	.byte $84,$05,$16,$16,$05,$16,$16,$21,$16,$16,$04,$04,$04,$04,$21,$16
	.byte $16,$05,$16,$16,$21,$16,$16,$05,$05,$21,$16,$16,$05,$16,$16,$21
	.byte $16,$16,$04,$04,$04,$04,$21,$16,$16,$05,$16,$16,$21,$16,$16,$05
	.byte $04,$81
@ref109:
	.byte $80,$21,$84,$16,$16,$05,$16,$16,$21,$16,$16,$04,$04,$04,$04,$21
	.byte $16,$16,$05,$16,$16,$21,$16,$16,$05,$05,$21,$16,$16,$05,$16,$16
	.byte $21,$16,$16,$04,$04,$04,$04,$21,$16,$16,$05,$16,$16,$21,$16,$16
	.byte $05,$04,$81
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
@ref120:
	.byte $86,$04,$8d,$10,$8d,$04,$8d,$10,$8d,$04,$8d,$10,$95,$04,$85,$11
	.byte $08,$89
@ref121:
	.byte $04,$8d,$10,$8d,$04,$8d,$10,$8d,$04,$8d,$10,$95,$04,$85,$11,$08
	.byte $89
	.byte $ff,$11
	.word @ref121
@ref123:
	.byte $04,$8d,$10,$8d,$04,$8d,$10,$8d,$04,$8d,$10,$8d,$04,$8d,$10,$8d
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$31
	.word @ref109
	.byte $ff,$11
	.word @ref120
	.byte $ff,$11
	.word @ref121
	.byte $ff,$11
	.word @ref121
	.byte $ff,$10
	.word @ref123
@ref138:
	.byte $f9,$85
@ref139:
	.byte $f9,$85
@ref140:
	.byte $f9,$85
@ref141:
	.byte $f9,$85
@ref142:
	.byte $f9,$85
@ref143:
	.byte $8d
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref144:
	.byte $f9,$85
@ref145:
	.byte $f9,$85
@ref146:
	.byte $f9,$85
@ref147:
	.byte $f9,$85
@ref148:
	.byte $f9,$85
@ref149:
	.byte $f9,$85
@ref150:
	.byte $f9,$85
@ref151:
	.byte $f9,$85
@ref152:
	.byte $f9,$85
@ref153:
	.byte $f9,$85
@ref154:
	.byte $f9,$85
@ref155:
	.byte $f9,$85
@ref156:
	.byte $f9,$85
@ref157:
	.byte $f9,$85
@ref158:
	.byte $f9,$85
@ref159:
	.byte $f9,$85
@ref160:
	.byte $f9,$85
@ref161:
	.byte $f9,$85
@ref162:
	.byte $f9,$85
@ref163:
	.byte $f9,$85
@ref164:
	.byte $f9,$85
@ref165:
	.byte $f9,$85
@ref166:
	.byte $f9,$85
@ref167:
	.byte $f9,$85
@ref168:
	.byte $f9,$85
@ref169:
	.byte $f9,$85
@ref170:
	.byte $f9,$85
@ref171:
	.byte $f9,$85
@ref172:
	.byte $f9,$85
@ref173:
	.byte $f9,$85
@ref174:
	.byte $f9,$85
@ref175:
	.byte $f9,$85
@ref176:
	.byte $f9,$85
@ref177:
	.byte $f9,$85
@ref178:
	.byte $f9,$85
@ref179:
	.byte $8d
	.byte $fd
	.word @song0ch4loop
